# Generated by Django 4.2 on 2025-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, help_text='LINEユーザーID（連携時に設定）', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['line_user_id'], name='users_line_us_d15412_idx'),
        ),
    ]
