providers = ['python']

[variables]
NIXPACKS_PYTHON_VERSION = '3.12'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'

[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["libpq-dev", "gcc"]

[phases.build]
cmds = [
    "ls -la",
    "ls -la frontend/",
    "cd frontend && ls -la && npm install && npm run build && cd .."
]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py && gunicorn daily_dish_project.wsgi:application --bind 0.0.0.0:$PORT"