providers = ["python", "node"]

[variables]
PG_CONFIG = "/nix/store/*/bin/pg_config"

[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "cd frontend && npm ci && npm run build && cd .."

[start]
cmd = "mkdir -p staticfiles && python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py && gunicorn daily_dish_project.wsgi:application --bind 0.0.0.0:$PORT"