providers = ["python", "node"]

[phases.setup]
aptPkgs = ["libpq-dev", "gcc"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "cd frontend && npm ci && npm run build && cd .. && mkdir -p staticfiles"

[start]
cmd = "mkdir -p staticfiles && python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py && gunicorn daily_dish_project.wsgi:application --bind 0.0.0.0:$PORT"