providers = ['python']

[variables]
NIXPACKS_PYTHON_VERSION = '3.12'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'

[phases.setup]
nixPkgs = ["...", "nodejs", "python3"]
aptPkgs = ["libpq-dev", "gcc"]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "ls -la frontend/dist/"
]

[start]
cmd = "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 create_superuser.py && gunicorn daily_dish_project.wsgi:application --bind 0.0.0.0:$PORT"