[providers]
python = { version = "3.12" }
node = { version = "20" }

[phases.setup]
aptPkgs = ["libpq-dev", "gcc"]

[phases.build]
cmd = """
cd frontend && npm ci && npm run build && cd ..
"""

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py && gunicorn daily_dish_project.wsgi:application --bind 0.0.0.0:$PORT"